### ISSUE TITLE
ICAR-ENSO dataset

### ISSUE THREAD

**Issue by MSrobt** [seominseok0429/Implicit-Stacked-Autoregressive-Model-for-Video-Prediction#4]
Thank you for sharing the code

I can't find the ICAR-ENSO dataset. I'm very interested in your work. If possible, could you please share the ICAR-ENSO dataset, corresponding hyperparameter and data preprocessing program with me.

**Comment by seominseok0429** [comment]
Thank you @MSrobt for interested our work!!!

We received pre-processed dataset from other authors. So I will share the dataset and code after ask other authors.

as soon as possible, i will note you!

Thank you!

**Comment by seominseok0429** [comment]
I will share the code this week!! Please wait just four days!

**Comment by MSrobt** [comment]
thank you！
