### ISSUE TITLE
the code is inconsistent with the paper

### ISSUE THREAD

**Issue by qzhai** [seominseok0429/Implicit-Stacked-Autoregressive-Model-for-Video-Prediction#9]
Hi,

Thank you for sharing the exciting work, I find several confusion points between the code and the paper.

1. the Mask in Algorithm1 is not implemented, and the mask_token in code is only replaced with the feature embedding produced by LP(learned prior module).
2. the features of GT future frame are not extracted through Encoder, and the features of preducted future frame are not supervised.
4. according to the inference process, the final prediction is generated by the LP module, but the LP recieves the outputs and generates the features, how to understand the Figure 3 in paper.
5. the test() function isn't working, as the model.py (line 130) need a valid variable t (not None) as input.

**Comment by seominseok0429** [comment]
First of all, thank you very much for your interest in our research.

The current version of the code is the changed version of the code after receiving code and paper reviews.

Our old version of the code is like the link below. We tested and confirmed that the current version has faster convergence.

https://github.com/seominseok0429/Implicit-Stacked-Autoregressive-Model-for-Video-Prediction/commit/2548780b0aef8313bea543313017ef7bcc0914a6

The test code will be modified. Thanks for pointing out what went wrong.

thank you.

best.

minseok.
